# Generated by Django 5.2.8 on 2025-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='status',
            field=models.BooleanField(),
        ),
    ]
