# Generated by Django 6.0 on 2025-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historico_valor_alter_sensores_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsaveis',
            old_name='responsavel',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='unidade_med',
        ),
        migrations.AddField(
            model_name='sensores',
            name='unidade_medida',
            field=models.CharField(default='exist', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locais',
            name='local',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='mac_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
